# include:
#   - project: 'snapp-supply/devops/gitlab-ci-files'
#     file:
#       - 'samples/default.yml'

include:
  # Stages
  - project: 'snapp-supply/devops/gitlab-ci-files'
    file:
      - 'general/.gitlab-ci-stages.yml'
  # Staging
  - project: 'snapp-supply/devops/gitlab-ci-files'
    file:
      - 'snappcloud/.gitlab-ci-staging-build.yml'
      # Snappcloud Deploy
      - 'snappcloud/.gitlab-ci-staging-pre-deploy.yml'
      - 'snappcloud/.gitlab-ci-staging-deploy.yml'
      - 'snappcloud/.gitlab-ci-staging-deploy-check.yml'
      ### Security
      # # sast
      # - 'snappcloud/security/sonarqube/sonarqube-staging.yml'
      # - 'snappcloud/security/gitleaks/gitleaks.yml'
      # - 'snappcloud/security/semgrep/semgrep-staging.yml'
      # # sbom
      # - 'snappcloud/security/trivy/trivy-staging.yml'
      # - 'snappcloud/security/grype/grype.yml'
      # Radar
  # Production
  - project: 'snapp-supply/devops/gitlab-ci-files'
    file:
      - 'snappcloud/.gitlab-ci-production-build.yml'
      - 'snappcloud/.gitlab-ci-production-release-git.yml'
      - 'snappcloud/.gitlab-ci-production-release-images.yml'
      # Snappcloud Deploy
      - 'snappcloud/.gitlab-ci-production-pre-deploy.yml'
      - 'snappcloud/.gitlab-ci-production-deploy.yml'
      - 'snappcloud/.gitlab-ci-production-deploy-check.yml'
  # Discord notification
  - project: 'snapp-supply/devops/gitlab-ci-files'
    file:
      - 'snappcloud/.gitlab-ci-production-notify-discord.yml'

radar:
  variables:
    CONTAINER_SCANNING_IMAGE_NAME: "$IMAGE_ADDR"
    CONTAINER_SCANNING_REGISTRY: "$REGISTRY_URL"
    CONTAINER_SCANNING_USERNAME: "$REGISTRY_USER"
    CONTAINER_SCANNING_PASSWORD: "$REGISTRY_PASS"
  stage: radar
  trigger:
      include: 
        - project: 'security/AppSec'
          file: 
          - 'sast.yml'
          - 'secret-detection.yml'
          - 'iac-scanning.yml'
          - 'sca.yml'
          - 'container-scanning.yml'
